import torch
import torch.nn as nn
import torch.nn.functional as f


device = 'cuda' if torch.cuda.is_available() else 'cpu'


class KPPredictor(nn.Module):
    """
    Class representing the Key-Point Predictor to be used.
    """

    def __init__(self, in_channels=256, nkp=32, stdev=0.1, kpp_name='Key-Point Predictor'):
        """
        Initializes the Generator network.
        :param stdev: (float, optional) The standard deviation to be used to generate the Gaussian heatmaps
                      (default 0.1).
        :param kpp_name: (str, optional) The name of the network (default 'Video Generator').
        """
        super(KPPredictor, self).__init__()
        self.kpp_name = kpp_name

        self.stdev = stdev
        self.nkp = nkp

        # definition of all layers
        self.conv3d_1 = nn.Conv3d(in_channels=in_channels, out_channels=128, kernel_size=(3, 3, 3),
                                  stride=(1, 1, 1), padding=(1, 1, 1))
        self.conv3d_2 = nn.Conv3d(in_channels=128, out_channels=64, kernel_size=(3, 3, 3),
                                  stride=(1, 1, 1), padding=(1, 1, 1))
        self.conv3d_3 = nn.Conv3d(in_channels=64, out_channels=self.nkp, kernel_size=(3, 3, 3),
                                  stride=(1, 1, 1), padding=(1, 1, 1))

        # print('%s Model Successfully Built \n' % self.kpp_name)

    def forward(self, x):
        """
        Function to compute a single forward pass through the network, according to the architecture.
        :param x: (tensor) The input tensor from which to predict key-points.
                   Must be a tensor of shape: (bsz, 32, 16, 14, 14) for this application.
        :return: A tensor representing the video generated by the network.
                 Shape of output is: (bsz, 3, 8/16, 112, 112) for this application.
        """
        x = self.conv3d_1(x)
        x = f.interpolate(x, size=(8, 14, 14), mode='trilinear')
        x = self.conv3d_2(x)
        x = f.interpolate(x, size=(16, 14, 14), mode='trilinear')
        x = self.conv3d_3(x)

        bsz, nkp, frames, height, width = x.size()

        gauss_mean = KPPredictor.get_gauss_mean(x)
        gauss_heatmaps = KPPredictor.get_gaussian_heatmaps(mean=gauss_mean, stdev=self.stdev, map_size=(height, width))

        return gauss_heatmaps

    @staticmethod
    def get_gauss_mean(x):
        bsz, nkp, frames, height, width = x.size()
        y_coord = KPPredictor.get_coord(x, other_axis=4, axis_size=height)  # bsz, nkp, frames
        x_coord = KPPredictor.get_coord(x, other_axis=3, axis_size=width)  # bsz, nkp, frames
        y_coord, x_coord = torch.unsqueeze(y_coord, dim=3), torch.unsqueeze(x_coord, dim=3)

        gauss_mean = torch.cat([y_coord, x_coord], dim=3)

        return gauss_mean

    @staticmethod
    def get_coord(tensor, other_axis, axis_size):
        coord_probs = torch.mean(tensor, dim=other_axis, keepdim=False)  # bsz, nkp, frames, h/w
        coord_probs = nn.Softmax(dim=3)(coord_probs)  # dim=h/w; softmax along h/w

        coords = torch.linspace(start=-1.0, end=1.0, steps=axis_size, dtype=torch.float32)  # h/w
        coords = torch.reshape(coords, shape=(1, 1, 1, axis_size))  # bsz=1, nkp=1, frames=1, h/w
        coords = coords.to(device)

        coord = torch.sum(coord_probs * coords, dim=3)  # dim=h/w; bsz, nkp, frames

        return coord

    @staticmethod
    def get_gaussian_heatmaps(mean, stdev, map_size):
        height, width = map_size
        mean_y, mean_x = mean[:, :, :, 0:1], mean[:, :, :, 1:2]  # bsz, nkp, frames, h/w=1

        y = torch.linspace(start=-1.0, end=1.0, steps=height, dtype=torch.float32)  # h
        x = torch.linspace(start=-1.0, end=1.0, steps=width, dtype=torch.float32)  # w
        y = torch.reshape(y, shape=(1, 1, 1, height))  # bsz=1, nkp=1, frames=1, h
        x = torch.reshape(x, shape=(1, 1, 1, width))  # bsz=1, nkp=1, frames=1, w
        y, x = y.to(device), x.to(device)

        gauss_y = torch.exp(-(((y - mean_y) * (y - mean_y)) / (2 * stdev * stdev)))  # bsz, nkp, frames, h
        gauss_x = torch.exp(-(((x - mean_x) * (x - mean_x)) / (2 * stdev * stdev)))  # bsz, nkp, frames, w
        gauss_y = torch.unsqueeze(gauss_y, dim=4)  # bsz, nkp, frames, h, w=1
        gauss_x = torch.unsqueeze(gauss_x, dim=3)  # bsz, nkp, frames, h=1, w

        gauss_map = torch.matmul(gauss_y, gauss_x)  # bsz, nkp, frames, h, w

        return gauss_map


# if __name__ == "__main__":
#     print_summary = True
#
#     kpp = KPPredictor()
#
#     if print_summary:
#         summary(kpp, input_size=(1, 16, 14, 14))
