# phase 2

import torch
import torch.nn as nn
# from torchsummary import summary

device = 'cuda' if torch.cuda.is_available() else 'cpu'


class Expander(nn.Module):
    """
    Class representing the Expander network to be used.
    """

    def __init__(self, vp_value_count, out_frames, out_size, ex_name='Viewpoint Expander'):
        super(Expander, self).__init__()
        self.ex_name = ex_name

        self.vp_value_count = vp_value_count
        self.out_frames = out_frames
        self.out_size = out_size

        # definition of all network layers
        self.conv3d_1a = nn.Conv3d(in_channels=self.vp_value_count, out_channels=4, kernel_size=(3, 3, 3),
                                   stride=(1, 1, 1), padding=(1, 1, 1))
        self.conv3d_1b = nn.Conv3d(in_channels=4, out_channels=self.vp_value_count, kernel_size=(3, 3, 3),
                                   stride=(1, 1, 1), padding=(1, 1, 1))

        # print('%s Model Successfully Built \n' % self.ex_name)

    def forward(self, x):
        """
        Function to compute a single forward pass through the network, according to the architecture.
        :param x: (tensor) The input tensor from which a video will be generated.
                   Must be a tensor of shape: (bsz, 1536, 7, 7) for this application.
        :return: A tensor representing the video generated by the network.
                 Shape of output is: (bsz, 3, 8/16, 112, 112) for this application.
        """
        x = self.expand_vp(x)

        x = self.conv3d_1a(x)
        x = self.conv3d_1b(x)

        return x

    def expand_vp(self, vp):
        bsz = vp.size()[0]

        buffer = torch.zeros(bsz, self.vp_value_count, self.out_frames, self.out_size, self.out_size)
        for b in range(self.vp_value_count):
            for c in range(self.out_frames):
                for d in range(self.out_size):
                    for e in range(self.out_size):
                        buffer[:, b, c, d, e] = vp
        buffer = buffer.to(device)

        return buffer


# if __name__ == "__main__":
#     print_summary = True
#
#     ex = Expander(vp_value_count=1, out_frames=16, out_size=28)
#
#     if print_summary:
#         summary(ex, input_size=(1))
